// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipes.Data;

namespace Recipes.Data.Migrations
{
    [DbContext(typeof(RecipeContext))]
    partial class RecipeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Recipes.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 12, 23, 16, 56, 8, 351, DateTimeKind.Local).AddTicks(3161),
                            CreatorId = 4,
                            Name = "Salads"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 12, 23, 16, 56, 8, 351, DateTimeKind.Local).AddTicks(3540),
                            CreatorId = 4,
                            Name = "Soups"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 12, 23, 16, 56, 8, 351, DateTimeKind.Local).AddTicks(3549),
                            CreatorId = 4,
                            Name = "Main dishes"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2020, 12, 23, 16, 56, 8, 351, DateTimeKind.Local).AddTicks(3552),
                            CreatorId = 4,
                            Name = "Vegetarian"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2020, 12, 23, 16, 56, 8, 351, DateTimeKind.Local).AddTicks(3554),
                            CreatorId = 4,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2020, 12, 23, 16, 56, 8, 351, DateTimeKind.Local).AddTicks(3556),
                            CreatorId = 4,
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("Recipes.Data.Models.FavouriteRecipe", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("FavouriteRecipes");
                });

            
            modelBuilder.Entity("Recipes.Data.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TitleImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2020, 12, 23, 16, 56, 8, 351, DateTimeKind.Local).AddTicks(7645),
                            CreatorId = 1,
                            Description = "Traditional Bulgarian dish",
                            Name = "Musaka",
                            TitleImageUrl = "https://i0.wp.com/www.kashkaval-tourist.com/wp-content/uploads/2014/02/musaka.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            CreatedOn = new DateTime(2020, 12, 23, 16, 56, 8, 351, DateTimeKind.Local).AddTicks(7661),
                            CreatorId = 3,
                            Description = "Classic chocolate cake",
                            Name = "Chocolate cake",
                            TitleImageUrl = "https://cdn.sallysbakingaddiction.com/wp-content/uploads/2013/04/triple-chocolate-cake-4.jpg"
                        });
                });

            modelBuilder.Entity("Recipes.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 12, 23, 16, 56, 8, 348, DateTimeKind.Local).AddTicks(4843),
                            Description = "I'm 20 years old",
                            Email = "someMail@abv.bg",
                            ImageUrl = "https://p7.hiclipart.com/preview/780/873/166/cooking-mama-world-kitchen-cooking-mama-lets-cookuff01-puzzle-cooking-mama-cooking-png-photo-thumbnail.jpg",
                            Password = "123FDGEF",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 12, 23, 16, 56, 8, 350, DateTimeKind.Local).AddTicks(2913),
                            Description = "Hello there",
                            Email = "other@abv.bg",
                            ImageUrl = "https://p7.hiclipart.com/preview/780/873/166/cooking-mama-world-kitchen-cooking-mama-lets-cookuff01-puzzle-cooking-mama-cooking-png-photo-thumbnail.jpg",
                            Password = "12FddFDDGEF2",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 12, 23, 16, 56, 8, 350, DateTimeKind.Local).AddTicks(2935),
                            Description = "I'm new here",
                            Email = "email@abv.bg",
                            ImageUrl = "https://p7.hiclipart.com/preview/780/873/166/cooking-mama-world-kitchen-cooking-mama-lets-cookuff01-puzzle-cooking-mama-cooking-png-photo-thumbnail.jpg",
                            Password = "werDGEF2",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2020, 12, 23, 16, 56, 8, 350, DateTimeKind.Local).AddTicks(2938),
                            Description = "Admin",
                            Email = "email@abv.bg",
                            ImageUrl = "https://p7.hiclipart.com/preview/780/873/166/cooking-mama-world-kitchen-cooking-mama-lets-cookuff01-puzzle-cooking-mama-cooking-png-photo-thumbnail.jpg",
                            Password = "ggdsg@gmail.com",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Recipes.Data.Models.Category", b =>
                {
                    b.HasOne("Recipes.Data.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Recipes.Data.Models.FavouriteRecipe", b =>
                {
                    b.HasOne("Recipes.Data.Models.Recipe", "Recipe")
                        .WithMany("FavouriteRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recipes.Data.Models.User", "User")
                        .WithMany("FavouriteRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recipes.Data.Models.Recipe", b =>
                {
                    b.HasOne("Recipes.Data.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recipes.Data.Models.User", "Creator")
                        .WithMany("Recipes")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Recipes.Data.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Recipes.Data.Models.Recipe", b =>
                {
                    b.Navigation("FavouriteRecipes");
                });

            modelBuilder.Entity("Recipes.Data.Models.User", b =>
                {
                    b.Navigation("FavouriteRecipes");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
